In [1]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
d=a-b
e=a*b
f=a@b
a_transpose=a.T
b_transpose=b.T
print("Addition:")
print(c)
print("\nSubtraction:")
print(d)
print("\nMultiplication(element wise):")
print(e)
print("\nMatrix multiplication:")
print(f)
print("\nTranspose:")
print(a_transpose) 
print(b_transpose)




Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication(element wise):
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Transpose:
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [4]:
import numpy as np
#create a sample matrix
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform SVD
u,s,vt=np.linalg.svd(x)
#choose the number of components to keep
n_components=2
#reconstruct the matrix with reduced dimensions
x_reconstructed=np.dot(u[:,:n_components],np.dot(np.diag(s[:n_components]),vt[:n_components,:]))
print("Original matrix:")
print(x)
print("\nReconstructed matrix(with reduced dimensions):")
print(x_reconstructed)


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
